version: '3.7'
services:
  api:
    image: api
    build: ./
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - .:/app
    tty: true
  db:
    image: postgres
    env_file:
      - .env
    ports:
        - 5432:5432
  redis:
      image: redis
      ports:
        - 6379:6379
  pgadmin:
      image: dpage/pgadmin4
      env_file:
      - .env
      ports:
        - 8080:80
      volumes:
        - ./pgadmin4/servers.json:/pgadmin4/servers.json
